sudo: false
language: node_js
node_js:
  - "6"
  - "5"
  - "4"
  - "node"

cache:
  directories:
    - bower_components
    - node_modules

install:
  - npm install -g npm@latest
  - npm install -g bower gulp
  - npm install

script:
  - npm run build
  - npm run eslint